### ISSUE TITLE
Broken code in JunimoServer.dll: reference to StardewValley.WorldMaps.WorldMapManager.GetPositionData (no such method).

### ISSUE THREAD

**Issue by ShadowJonathan** [stardew-valley-dedicated-server/server#13]
This is what I get when loading the server, when starting a clean install from the latest stardew valley version (1.6.14).

I see another mod reference this problem; https://github.com/Annosz/UIInfoSuite2/pull/635

Some code would need to be updated to make this work, but I'm unsure what.

**Comment by JulianVallee** [comment]
Thanks a lot for the report, mod updated for SDV 1.6.15 in #14 and should work again :)

**Comment by ShadowJonathan** [comment]
Don't forget to upload a new docker version, the latest seems to be from 6 months ago

(though this has also been resolved less than an hour ago, I assume you're on it)

**Comment by JulianVallee** [comment]
Ahh thanks for the reminder, admittedly it was a bit on the backburner, but setting up CI/CD next to keep it up-to-date etc.

**Comment by ShadowJonathan** [comment]
(This now lives in #17)
